import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/assets/globals.css";
import { SideBar } from "@/app/ui/side-bar";
import { NavBar } from "@/app/ui/nav-bar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "BWS Financial",
  description: "Generated by BWSoft",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full bg-gray-100">
      <body className={`${inter.className} h-full`}>
        <SideBar />
        <div className="lg:pl-72">
          <NavBar />

          <main className="py-10">
            <div className="px-4 sm:px-6 lg:px-8">{children}</div>
          </main>
        </div>
      </body>
    </html>
  );
}
