import "@/app/assets/globals.css";
import { NavBar } from "@/app/ui/nav-bar";
import { SideBar } from "@/app/ui/side-bar";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import NextTopLoader from "nextjs-toploader";
import { Toaster } from "../ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "BWS Financial",
  description: "Generated by BWSoft",
};

export default function RootLayout({
  children,
  modal,
}: {
  children: React.ReactNode;
  modal: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full bg-gray-50">
      {modal}
      <body className={`${inter.className} h-full`}>
        <NextTopLoader height={4} />
        <SideBar />
        <div className="lg:pl-72">
          <NavBar />

          <main>
            <div className="p-4 sm:p-6 lg:p-8">{children}</div>
          </main>
        </div>
        <Toaster />
      </body>
    </html>
  );
}
